---
- src: https://github.com/jtyr/ansible-config_encoder_filters
  version: v1.20
  name: jtyr.config_encoder_filters

- src: https://github.com/vbotka/ansible-lib
  version: 1.1.0
  name: vbotka.ansible_lib
...
