---

- name: Configure parameters in{{apache_conf_path}}/httpd.conf
  lineinfile: >
    dest="{{apache_conf_path}}/httpd.conf"
    regexp="{{item.regexp}}"
    line="{{item.line}}"
    insertbefore="BOF"
    backup="yes"
  with_items:
    - { regexp: "^ServerName ", line: "ServerName {{apache_ServerName}}"}
    - { regexp: "^ServerAdmin ", line: "ServerAdmin {{apache_ServerAdmin}}"}
  notify: reload apache
  tags: config_httpd_conf

- name: Configure Direcotries in {{apache_conf_path}}/httpd.conf
  blockinfile:
    dest: "{{apache_conf_path}}/httpd.conf"
    backup: "yes"
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    insertafter: "# <Directory> blocks below."
    block: |
      {{item}}
  with_items: "{{apache_Directory_blocks}}"
  notify: reload apache
  tags: config_https_conf_directory_blocks
