---

- name: "config_httpd-ssl_conf: Include extra/httpd-ssl.conf in {{ apache_conf_path }}/httpd.conf"
  lineinfile:
    dest: "{{ apache_conf_path }}/httpd.conf"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    insertbefore: "BOF"
    backup: yes
  with_items: "{{ apache_httpd_conf_ssl }}"
  when: apache_ssl
  notify: reload apache

- name: "config_httpd-ssl_conf: Configure {{ apache_conf_path }}/extra/httpd-ssl.conf"
  lineinfile:
    dest: "{{ apache_conf_path }}/extra/httpd-ssl.conf"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    insertbefore: "BOF"
    backup: yes
  with_items: "{{ apache_httpd_conf_ssl_extra }}"
  when: apache_ssl
  notify: reload apache

# EOF
...
