---

- name: Configure modules in{{apache_conf_path}}/httpd.conf
  lineinfile: >
    dest="{{apache_conf_path}}/httpd.conf"
    regexp="{{item.regexp}}"
    line="{{item.line}}"
    insertbefore="BOF"
    backup="yes"
  with_items:
    - { regexp: "^LoadModule socache_shmcb_module ",
        line: "LoadModule socache_shmcb_module libexec/{{apache_version}}/mod_socache_shmcb.so"}
  notify: reload apache
  tags: config_httpd-modules_conf


- name: Configure SSL module in{{apache_conf_path}}/httpd.conf
  lineinfile: >
    dest="{{apache_conf_path}}/httpd.conf"
    regexp="{{item.regexp}}"
    line="{{item.line}}"
    insertbefore="BOF"
    backup="yes"
  with_items:
    - { regexp: "^LoadModule ssl_module ",
        line: "LoadModule ssl_module libexec/{{apache_version}}/mod_ssl.so"}
  when: apache_ssl == "yes"
  notify: reload apache
  tags: config_httpd-module-ssl_conf


- name: Configure PHP module in{{apache_conf_path}}/httpd.conf
  lineinfile: >
    dest="{{apache_conf_path}}/httpd.conf"
    regexp="{{item.regexp}}"
    line="{{item.line}}"
    insertbefore="BOF"
    backup="yes"
  with_items:
    - { regexp: "^LoadModule php5_module ",
        line: "LoadModule php5_module        libexec//{{apache_version}}/libphp5.so"}
  when: apache_php == "yes"
  notify: reload apache
  tags: config_httpd-module-php_conf
