---

- name: "httpd-modules_conf: Configure modules in {{ apache_conf_path }}/httpd.conf"
  lineinfile:
    dest: "{{ apache_conf_path }}/httpd.conf"
    regexp: "^LoadModule {{ item.module }}"
    line: "LoadModule {{ item.module }} libexec/{{ apache_dir }}/{{ item.mod }}"
    insertbefore: "LoadModule"
    backup: "{{ apache_backup_conf }}"
  loop: "{{ apache_httpd_conf_modules }}"
  notify: reload apache

- name: "httpd-modules_conf: Configure PHP in {{ apache_conf_path }}/Includes/php.conf"
  blockinfile:
    dest: "{{ apache_conf_path }}/Includes/php.conf"
    block: |
      <IfModule dir_module>
        DirectoryIndex index.html index.php
      </IfModule>
      <FilesMatch "\.php$">
        SetHandler application/x-httpd-php
      </FilesMatch>
      <FilesMatch "\.phps$">
        SetHandler application/x-httpd-php-source
      </FilesMatch>
    owner: "root"
    group: "www"
    mode: "0640"
    create: yes
    backup: "{{ apache_backup_conf }}"
  when: apache_php
  notify: reload apache

# EOF
...
