---

- name: "httpd-vhosts: Create directories for virtual hosts"
  file:
    state: directory
    path: "{{ item.DocumentRoot }}"
    owner: "{{ apache_data_owner }}"
    group: "{{ apache_data_group }}"
    mode: "{{ apache_dir_mode }}"
  loop: "{{ apache_vhost }}"
  when: item.create_document_root|default(False)

- name: "httpd-vhosts: Configure virtual hosts in {{ apache_conf_path }}/extra/"
  template:
    src: "vhost.j2"
    dest: "{{ apache_conf_path }}/extra/{{ item.ServerName }}.conf"
    owner: "{{ apache_data_owner }}"
    group: "{{ apache_data_group }}"
    mode: "{{ apache_data_mode }}"
    backup: "{{ apache_backup_conf }}"
  loop: "{{ apache_vhost }}"
  notify: reload apache

- name: "httpd-vhosts: Incl virtual hosts in {{ apache_conf_path }}/httpd.conf"
  lineinfile:
    dest: "{{ apache_conf_path }}/httpd.conf"
    regexp: "^Include etc/apache{{ apache_version }}/extra/{{ item.ServerName }}.conf"
    line: "Include etc/apache{{ apache_version }}/extra/{{ item.ServerName }}.conf"
    insertbefore: "BOF"
    backup: "{{ apache_backup_conf }}"
  loop: "{{ apache_vhost }}"
  notify: reload apache

# EOF
...
