---

- name: "httpd-confd: Configure virtual hosts from {{ apache_confd_dir_vhosts }}"
  ansible.builtin.import_tasks: "httpd-confd-vhosts.yml"
  tags: apache-httpd-confd-vhosts

- name: "httpd-confd: Configure includes from {{ apache_confd_dir_sections }}"
  ansible.builtin.import_tasks: "httpd-confd-includes.yml"
  tags: apache-httpd-confd-includes

# EOF
...
