---

- name: "httpd-modules: Load modules in {{ apache_conf_path }}/httpd.conf"
  lineinfile:
    dest: "{{ apache_conf_path }}/httpd.conf"
    regexp: "^\\s*#*\\s*LoadModule {{ item.module }}"
    line: "    LoadModule {{ item.module }} libexec/{{ apache_dir }}/{{ item.mod }}"
    insertbefore: "LoadModule"
    backup: "{{ apache_backup_conf }}"
  loop: "{{ apache_httpd_conf_modules }}"
  when: item.present|default(true)
  notify: restart apache

- name: "httpd-modules: Unload modules in {{ apache_conf_path }}/httpd.conf"
  lineinfile:
    dest: "{{ apache_conf_path }}/httpd.conf"
    regexp: "^\\s*#*\\s*LoadModule {{ item.module }}"
    line: "    # LoadModule {{ item.module }}"
    insertbefore: "LoadModule"
    backup: "{{ apache_backup_conf }}"
  loop: "{{ apache_httpd_conf_modules }}"
  when: not item.present|default(true)
  notify: restart apache

- name: "httpd-modules: Config PHP in {{ apache_conf_path }}/Includes/php.conf"
  blockinfile:
    dest: "{{ apache_conf_path }}/Includes/php.conf"
    block: |
      <IfModule dir_module>
        DirectoryIndex index.html index.php
      </IfModule>
      <FilesMatch "\.php$">
        SetHandler application/x-httpd-php
      </FilesMatch>
      <FilesMatch "\.phps$">
        SetHandler application/x-httpd-php-source
      </FilesMatch>
    owner: "root"
    group: "www"
    mode: "0640"
    create: "yes"
    backup: "{{ apache_backup_conf }}"
  when: apache_php
  notify: restart apache

# EOF
...
