---

- name: "config_httpd-modules_conf: Configure modules in {{ apache_conf_path }}/httpd.conf"
  lineinfile:
    dest: "{{ apache_conf_path }}/httpd.conf"
    regexp: "^LoadModule {{ item.module }}"
    line: "LoadModule {{ item.module }} libexec/{{ apache_dir }}/{{ item.mod }}"
    insertbefore: "BOF"
    backup: yes
  with_items: "{{ apache_httpd_conf_modules }}"
  notify: reload apache

# marker: "<!-- {mark} ANSIBLE MANAGED BLOCK -->"
# Including the marker resulted in error:
# "httpd: Syntax error on line 530 of
# /usr/local/etc/apache24/httpd.conf: Syntax error on line 1 of
# /usr/local/etc/apache24/Includes/php.conf:
# /usr/local/etc/apache24/Includes/php.conf:11: <!--> was not
# closed.\\n/usr/local/etc/apache24/Includes/php.conf:1: <!--> was not
# closed.\n"
- name: "config_httpd-modules_conf: Configure PHP in {{ apache_conf_path }}/Includes/php.conf"
  blockinfile:
    dest: "{{ apache_conf_path }}/Includes/php.conf"
    block: |
      <IfModule dir_module>
        DirectoryIndex index.html index.php
      </IfModule>
      <FilesMatch "\.php$">
        SetHandler application/x-httpd-php
      </FilesMatch>
      <FilesMatch "\.phps$">
        SetHandler application/x-httpd-php-source
      </FilesMatch>
    create: yes
    owner: "root"
    group: "www"
    mode: "0640"
  when: apache_php
  notify: reload apache

# EOF
...
