---
# tasks for vbotka.apache

- import_tasks: vars.yml
  tags: [ apache-vars, always ]

- import_tasks: debug.yml
  when: apache_debug
  tags: apache-debug

- import_tasks: packages.yml
  tags: apache-packages

- import_tasks: rcconf.yml
  tags: apache-rcconf

- import_tasks: httpd.yml
  tags: apache-httpd

- import_tasks: httpd-dirs.yml
  tags: apache-httpd-dirs

- import_tasks: httpd-modules.yml
  tags: apache-httpd-modules

- import_tasks: httpd-ssl.yml
  tags: apache-httpd-ssl

- import_tasks: httpd-vhosts.yml
  tags: apache-httpd-vhosts

# EOF
...
