---
# tasks for vbotka.apache

- name: "Apache: Debug"
  vars:
    msg: |
         apache_ServerName [ {{ apache_ServerName }} ]
         apache_ServerAdmin [ {{ apache_ServerAdmin }} ]
         apache_dir [ {{ apache_dir }} ]
         apache_service [ {{ apache_service }} ]
         apache_conf_path [ {{ apache_conf_path }} ]
         apache_httpd_conf [ {{ apache_httpd_conf | to_nice_yaml }} ]
         apache_ssl [ {{ apache_ssl }} ]
         apache_php [ {{ apache_php }} ]
         apache_packages [ {{ apache_packages }} ]
         apache_httpd_conf_modules [ {{ apache_httpd_conf_modules | to_nice_yaml }} ]
         apache_httpd_conf_ssl [ {{ apache_httpd_conf_ssl | to_nice_yaml }} ]
         apache_httpd_conf_ssl_extra [ {{ apache_httpd_conf_ssl_extra | to_nice_yaml }} ]
         apache_vhost [ {{ apache_vhost | to_nice_yaml }} ]
         apache_directory_blocks [ {{ apache_directory_blocks | to_nice_yaml }} ]
  debug: msg="{{ msg.split('\n') }}"
  when: apache_debug

- include: packages.yml
  tags: [ bsd_packages, bsd_ports, apache-packages ]

- include: config_rc_conf.yml
  tags: apache-config_rc

- include: config_httpd_conf.yml
  tags: apache-config_httpd

- include: config_httpd-dirs_conf.yml
  tags: apache-config_httpd-dirs

- include: config_httpd-modules_conf.yml
  tags: apache-config_httpd-modules

- include: config_httpd-ssl_conf.yml
  tags: apache-config_httpd-ssl

- include: config_httpd-vhosts_conf.yml
  tags: apache-config_httpd-vhosts

# EOF
...
