---

- name: Install {{ apache_package }}
  pkgng: >
    name="{{ item }}"
    state="present"
  with_items:
    - "{{ apache_package }}"
  when: freebsd_install_method == "packages"
  tags: bsd_packages

- name: Install mod_php{{ apache_php_version }}
  pkgng: >
    name="{{ item }}"
    state="present"
  with_items:
    - "{{ apache_php_package }}"
  when:
    - freebsd_install_method == "packages"
    - apache_php == "yes"
  tags: bsd_packages

- name: Install {{ apache_package }} (ports)
  portinstall: >
    name="{{ item }}"
    state="present"
    use_packages="{{ freebsd_use_packages }}"
  with_items:
    - "{{ apache_package }}"
  when: freebsd_install_method == "ports"
  tags: bsd_ports

- name: Install mod_php{{ apache_php_version }} (ports)
  portinstall: >
    name="{{ item }}"
    state="present"
    use_packages="{{ freebsd_use_packages }}"
  with_items:
    - "{{ apache_php_package }}"
  when:
    - freebsd_install_method == "ports"
    - apache_php == "yes"
  tags: bsd_ports

# EOF
...
