---

- name: Install apache
  pkgng: name='{{item}}' state='present'
  with_items:
    - '{{ apache_version }}'

- name: Install mod_php
  pkgng: name='{{item}}' state='present'
  with_items:
    - mod_php{{ apache_php_version }}
  when: apache_php == "yes"
