---

- name: "packages: Install packages"
  when: freebsd_install_method == "packages"
  pkgng:
    name: "{{ item }}"
  loop: "{{ apache_packages }}"
  register: result
  retries: "{{ freebsd_install_retries }}"
  until: result is succeeded
  delay: "{{ freebsd_install_delay }}"

- name: "packages: Install ports"
  when: freebsd_install_method == "ports"
  portinstall:
    name: "{{ item }}"
    use_packages: "{{ freebsd_use_packages|default(True) }}"
  loop: "{{ apache_packages }}"
  register: result
  retries: "{{ freebsd_install_retries }}"
  until: result is succeeded
  delay: "{{ freebsd_install_delay }}"

# EOF
...
