---

- name: Install apache
  pkgng: >
    name="{{item}}"
    state="present"
  with_items:
    - "{{ apache_version }}"
  when: freebsd_install_method == "packages"
  tags: packages

- name: Install mod_php
  pkgng: >
    name="{{item}}"
    state="present"
  with_items:
    - mod_php{{ apache_php_version }}
  when: ((freebsd_install_method == "packages") and (apache_php == "yes"))
  tags: packages

- name: Install apache (from ports)
  portinstall: >
    name="{{item}}"
    state="present"
    use_packages="{{freebsd_use_packages}}"
  with_items:
    - "www/{{ apache_version }}"
  when: freebsd_install_method == "ports"
  tags: ports

- name: Install mod_php (from ports)
  portinstall: >
    name="{{item}}"
    state="present"
    use_packages="{{freebsd_use_packages}}"
  with_items:
    - "www/mod_php{{ apache_php_version }}"
  when: ((freebsd_install_method == "ports") and (apache_php == "yes"))
  tags: ports

# EOF
