---

- name: "vars: Include OS vars"
  block:
    - name: "vars: Set variables for al_include_os_vars_path"
      set_fact:
        al_os_vars_path: "{{ role_path }}"
    - name: "vars: Include OS vars"
      include_role:
        name: vbotka.ansible_lib
        tasks_from: al_include_os_vars_path.yml

# - name: "vars: Default vars for
#                {{ ansible_os_family }}
#                {{ ansible_distribution }}
#                {{ ansible_distribution_release }}"
#   include_vars: "{{ item }}"
#   with_first_found:
#     - files:
#         - "{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml"
#         - "{{ ansible_distribution }}.yml"
#         - "{{ ansible_os_family }}.yml"
#         - "default.yml"
#       paths: "{{ role_path }}/vars/defaults"
#       skip: true
#
# - name: "vars: Custom vars for
#                {{ ansible_os_family }}
#                {{ ansible_distribution }}
#                {{ ansible_distribution_release }}"
#   include_vars: "{{ item }}"
#   with_first_found:
#     - files:
#         - "{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml"
#         - "{{ ansible_distribution }}.yml"
#         - "{{ ansible_os_family }}.yml"
#         - "default.yml"
#       paths: "{{ role_path }}/vars"
#       skip: true

# EOF
...
